#!/bin/sh

set -o errexit
set -o nounset

cd $(dirname $0)
export DOTFILES_ROOT=$(pwd)
cd control

# Pull in the common functions
. lib/common

# Cache some frequently-needed values
export OS=$(os)

# Figure out which machine this is and include the config for that machine.
. lib/machine_detection
case $(machine_id) in
	(mcdermottr.vm.bytemark.co.uk)
		# Personal laptop
		export GIT_EMAIL="conor@mcdermottroe.com"
		. machine/bytemark-box
		;;
	(F2B6560D-355B-5958-99BC-D9CEB875935D)
		# Personal laptop
		export GIT_EMAIL="conor@mcdermottroe.com"
		. machine/osx-personal
		;;
	(198B39C6-0787-5D18-8061-BDB34964C5A6|A01C25F1-845C-5D56-BC77-3F644CCAC650)
		# Work laptop
		export GIT_EMAIL="cmcdermottroe@engineyard.com"
		. machine/osx-work
		;;
	(*)
		abort "Unknown machine."
		;;
esac
