#!/bin/bash

. lib/file_management
. package/git

case $(os) in
    (Debian)
        package vim-nox
        ;;
    (*)
        package neovim
        ;;
esac
dotfile .vimrc

# Enable pathogen
if [ ! -L ~/.vim/autoload ]; then
    pushd ~/.vim
    cmd ln -fns bundle/vim-pathogen/autoload
    popd
fi

# Install packages
grep '^" PLUGIN:' "${DOTFILES_ROOT}/.vimrc" | \
    sed -e 's,^" PLUGIN:,,' | \
    while read -r plugin; do
        mkdir_p ~/.vim/bundle
        git_repo "https://${plugin}.git" ~/.vim/bundle
    done

# Add in the spellings
mkdir_p ~/.vim/spell
dotfile .vim/spell/en.utf-8.add
dotfile .vim/spell/en.utf-8.add.spl
